### ISSUE TITLE
Endless watch reboot with this watchface

### ISSUE THREAD

**Issue by serguHW3** [paraflu/JLWacthfaceIde-project-#1]
When creating this wf from scratch and loading in the HW3+, the watch enters in and endless reboot making it unusable.

Images are all png with transparency and 8bits/channel.

Thank you.
[0510eed027dfc0f7.zip](https://github.com/paraflu/JLWacthfaceIde-project-/files/14813333/0510eed027dfc0f7.zip)

**Comment by paraflu** [comment]
Try changing the frameType property to be consistent with the image. 2 for RGB, 8 rgba You see that in the image it is set to 2 while in frameType it is 8

**Comment by serguHW3** [comment]
Not exactly the case... see that there are no frameType=2

![image](https://github.com/paraflu/JLWacthfaceIde-project-/assets/165517907/820f8d6b-8b5b-48d1-83cd-58a05eb149c6)

**Comment by butfr0g** [comment]
Did you find a solution? I'm having the same issue

**Comment by paraflu** [comment]
@serguHW3 you have done a digit image with a 368x448 image ?

![image](https://github.com/paraflu/JLWacthfaceIde-project-/assets/3051226/ee11aa97-eae8-4efc-80ee-e1000669077f)


Try to reduce the size of the image to keep ligher the wf!

**Comment by paraflu** [comment]
> Did you find a solution? I'm having the same issue

try to send me an example (save project)

**Comment by serguHW3** [comment]
> @serguHW3 you have done a digit image with a 368x448 image ?
> 
> ![image](https://private-user-images.githubusercontent.com/3051226/318976314-ee11aa97-eae8-4efc-80ee-e1000669077f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzMxMzcsIm5iZiI6MTcxMjE3MjgzNywicGF0aCI6Ii8zMDUxMjI2LzMxODk3NjMxNC1lZTExYWE5Ny1lYWU4LTRlZmMtODBlZS1lMTAwMDY2OTA3N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTkzMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdhOWM4Zjg5ZDlmMGYyYjVkNTFmYWExMGI4ZGZlOTk2NzY1MDhjMmRlZjY4YzRiZGYwYWFiZGI0ZDBkYTliNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L1G0oK4XzSt6RAeya3bqctwKqY40xOxS6EoMWbULTV4)
> 
> Try to reduce the size of the image to keep ligher the wf!

I modified all images.
It doesn't install OK but at least the looping reboot is gone. I let you the Project.
[0510eed027dfc0f7.zip](https://github.com/paraflu/JLWacthfaceIde-project-/files/14857516/0510eed027dfc0f7.zip)

**Comment by paraflu** [comment]
well this is the problem

![image](https://github.com/paraflu/JLWacthfaceIde-project-/assets/3051226/c18368d5-b2a1-4db4-87fa-f4b929f1e329)

Some image have different size in the same frame

**Comment by serguHW3** [comment]
Wow!! So sensitive ..... XDDDD not sure if editor or watch but...
Thank you. I will check all elements and will report back.

**Comment by paraflu** [comment]
Can I close this issue?

**Comment by serguHW3** [comment]
Yes, please. Thank you

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
