### ISSUE TITLE
Weekdays issue

### ISSUE THREAD

**Issue by serguHW3** [paraflu/JLWacthfaceIde-project-#7]
Creating a dial with Spanish and English days of the week, found that:

1.- when watch is set up in Spanish, date shown is always the same: "dom" (Sunday).
After 2 days passed by, the same word remains 😋

2.- when watch is set up in English, date shown is in Spanish and correct. After 2 days checking, dates were correct "lun" and "mar" (as for Monday and Tuesday).

I made sure that I set up the days in their corresponding hex/bit positions.
Twice indeed. So, it points me to a incorrect programming. Can you please check this out?

Thanks for support.

**Comment by paraflu** [comment]
Have you an example to check?

**Comment by serguHW3** [comment]
This thread can be closed. Not an issue with software but with user 😋.

**Comment by serguHW3** [comment]
These are the languages supported and bytes (positions) used:

Chinese Simplified 0-6
English 7-13
German 14-20
Another chinese? 21-27
Spanish 28-34
Italian 35-41
French 42-48

If you want to use English and Spanish, as example, all bytes need to be fulfilled.
That means, images from 7 to 34.
